positional_goal_tolerance : 0.02
robot_type: "panda"
root_link: "panda_link0"
end_effector_link: "panda_vacuum"
orientation_helper_link: "panda_hand"
end_links: 
  - "panda_link5_offset"
  - "panda_vacuum"
  - "panda_vacuum_2"
  - "camera_link"
joint_names:
  - "panda_joint1"
  - "panda_joint2"
  - "panda_joint3"
  - "panda_joint4"
  - "panda_joint5"
  - "panda_joint6"
  - "panda_joint7"
num_obs : 20
angular_goal_tolerance: 0.1
collision_bodies:
  radius_body_panda_link0: 0.2
  radius_body_panda_link1: 0.1
  radius_body_panda_link2: 0.1
  radius_body_panda_link3: 0.1
  radius_body_panda_link4: 0.1
  radius_body_panda_link5: 0.1
  radius_body_panda_link6: 0.09
  radius_body_panda_link5_offset: 0.1
  radius_body_panda_link7: 0.1
  radius_body_panda_link8: 0.1
  radius_body_panda_vacuum: 0.02
  radius_body_panda_vacuum_2: 0.02
  radius_body_panda_hand: 0.08
  radius_body_camera_link: 0.03
collision_links: 
  - panda_link3
  - panda_link6
  - panda_link4
  - panda_vacuum
  - panda_vacuum_2
  - panda_hand
  - camera_link
self_collision_pairs: 
    panda_hand: 
      - panda_link2
      - panda_link4
      - panda_link5_offset
    panda_vacuum:
      - panda_link0
      - panda_link1
      - panda_link2
      - panda_link3
    panda_link6:
      - panda_link2
      - panda_link4
    camera_link:
      - panda_link2
