positional_goal_tolerance : 0.02
num_obs : 20
angular_goal_tolerance: 0.1
collision_bodies:
  radius_body_panda_link1: 0.1
  radius_body_panda_link2: 0.1
  radius_body_panda_link3: 0.1
  radius_body_panda_link4: 0.1
  radius_body_panda_link5: 0.1
  radius_body_panda_link6: 0.06
  radius_body_panda_link7: 0.1
  radius_body_panda_link8: 0.1
  radius_body_panda_vacuum: 0.02
  radius_body_panda_vacuum_2: 0.02
  radius_body_panda_hand: 0.08
collision_links: 
  - panda_link3
  - panda_link6
  - panda_link4
  - panda_vacuum
  - panda_vacuum_2
  - panda_hand
self_collision_pairs: 
    panda_hand: 
      - panda_link2
      - panda_link4
    panda_vacuum:
      - panda_link1
      - panda_link2
      - panda_link3
    panda_link6:
      - panda_link4
fabrics_geometries:
  collision_avoidance:
    geo:
      k: 1.0
      exp: 2.0
    fin:
      k: 1.0
      exp: 2.0
  self_collision_avoidance:
    geo:
      k: 1.0
      exp: 2.0
    fin:
      k: 1.0
      exp: 2.0
  limit:
    geo:
      k: 0.2
      exp: 2.0
    fin:
      k: 0.2
      exp: 2.0
