positional_goal_tolerance : 0.20
robot_type: "pointrobot"
planner_type: "nonholonomic"
degrees_of_freedom: 3
dim_state: 2
m_arm: 5.0
m_base: 5.0
m_rot: 0.5
k_geo_col: 0.1
k_fin_col: 0.1
l_offset: "0.5"
weight_goal0: 0.5
radius_obst: 0.2
obstacle_type: "sphere"
radius_body_base_link: 0.4
goal_indices: 
  - 0
  - 1
root_link: "world"
urdf_source: "/robot_description"
end_effector_link: 'base_link'
orientation_helper_link: "world"
end_links: 
  - "base_link"
num_sphere_obs : 1
num_box_obs : 0
angular_goal_tolerance: 0.1
collision_bodies:
  radius_body_ee_link: 0.4
collision_links: 
  - "base_link"
velocity_scaling: 1.0
velocity_limits:
  upper:
        - 0.3
        - 0.3
        - 0.3
  lower:
        - -0.3
        - -0.3
        - -0.3
joint_limits: [[-5, 5], [-5, 5]]
