#!/usr/bin/env python3
import rospy

from fabrics_bridge.boxer_fabrics import BoxerFabricsNode

if __name__ == "__main__":
    node = BoxerFabricsNode()
    try:
        node.run()
    except rospy.ROSInterruptException:
        pass

