#!/usr/bin/env python3
# ros imports
import rospy
from fabrics_msgs.msg import (
    FabricsJointSpaceGoal,
)
from geometry_msgs.msg import Point

from fabrics_bridge.utils import rectangle_spheres


class JointSpaceExampleClient(object):
    def __init__(self):
        rospy.init_node("client_node")
        self._rate = rospy.Rate(10)
        # if param num_obs is not set, default number of obstacles is 2
        self.init_publishers()
        
    def init_publishers(self):
        self._goal_publisher = rospy.Publisher(
            "fabrics/joint_space_goal", FabricsJointSpaceGoal, queue_size=10
        )

    def publish_goal(self):
        goal = FabricsJointSpaceGoal()
        goal.goal_joint_state.header.stamp = rospy.Time.now()
        goal.goal_joint_state.position = [-0.5, -0.9, 0.0, -1.501, 0.0, 1.8675, 1.0]
        goal.weight = 3.5
        goal.tolerance = 0.02
        self._goal_publisher.publish(goal)

    def run(self):
        while not rospy.is_shutdown():
            self.publish_goal()
            self._rate.sleep()


if __name__ == "__main__":
    client_node = JointSpaceExampleClient()
    try:
        client_node.run()
    except rospy.ROSInterruptException:
        pass
