#!/usr/bin/env python3
import rospy

from fabrics_bridge.kinova_fabrics import KinovaFabricsNode

if __name__ == "__main__":
    node = KinovaFabricsNode()
    try:
        node.run()
    except rospy.ROSInterruptException:
        pass

