#!/usr/bin/env python3
import rospy

from fabrics_bridge.panda_helper import PandaHelpersNode

if __name__ == "__main__":
    node = PandaHelpersNode()
    try:
        node.run()
    except rospy.ROSInterruptException:
        pass

