#!/usr/bin/env python3
import rospy

from fabrics_bridge.panda_plus_helper import PandaPlusHelpersNode

if __name__ == "__main__":
    node = PandaPlusHelpersNode()
    try:
        node.run()
    except rospy.ROSInterruptException:
        pass

