#!/usr/bin/env python3
import rospy

from fabrics_bridge.panda_fabrics import PandaFabricsNode

if __name__ == "__main__":
    node = PandaFabricsNode()
    try:
        node.run()
    except rospy.ROSInterruptException:
        pass

