#!/usr/bin/env python3
import rospy

from fabrics_bridge.panda_plus_fabrics import PandaPlusFabricsNode

if __name__ == "__main__":
    node = PandaPlusFabricsNode()
    try:
        node.run()
    except rospy.ROSInterruptException:
        pass

