#!/usr/bin/env python3
import rospy

from fabrics_bridge.pointrobot_fabrics import PointrobotFabricsNode

if __name__ == "__main__":
    node = PointrobotFabricsNode()
    try:
        node.run()
    except rospy.ROSInterruptException:
        pass

