name: fabrics_ros test

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        ros_distribution:
          - noetic
        include:
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-noetic-desktop-latest
            ros_distribution: noetic
            ros_version: 1
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: install non ros dependencies using requirments.txt (used when fabrics is not private anymore)
        run: pip3 install -r requirements.txt
      - name: setup directories
        run: mkdir -p karen_ws/src
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: karen_ws/src
          ref: ${{ github.event.pull_request.head.sha }}
      - name: build and test
        run: |
          chmod +x ${GITHUB_WORKSPACE}/karen_ws/src/.github/workflows/script.sh
          . ${GITHUB_WORKSPACE}/karen_ws/src/.github/workflows/script.sh
        shell: bash
